# Generated by lyra-client. Do not edit.
from typing import Literal, NotRequired, TypedDict, Unpack

from lyra.api import AsyncLyraClient, LyraClient

from ._metrics import AsyncMetrics, Metrics
from ._runtime import AsyncCatalogVerifier, CatalogVerifier


class _ClientOptions(TypedDict):
    timeout: NotRequired[float]
    headers: NotRequired[dict[str, str] | None]
    agent_api_key: NotRequired[str | None]
    secure: NotRequired[bool]
    verify_catalog: NotRequired[Literal["off", "warn", "error"]]


class Client:
    def __init__(
        self,
        host: str,
        **options: Unpack[_ClientOptions],
    ) -> None:
        core = LyraClient(
            host,
            options.get("timeout", 30.0),
            options.get("headers"),
            agent_api_key=options.get("agent_api_key"),
            secure=options.get("secure", True),
        )
        self._core = core
        self.health = core.health
        self.lookups = core.lookups
        self.catalog = core.catalog
        self.jobs = core.jobs
        self.results = core.results
        self.raw = core.raw
        verifier = CatalogVerifier(core, options.get("verify_catalog", "warn"))
        self.metrics = Metrics(core, verifier)


class AsyncClient:
    def __init__(
        self,
        host: str,
        **options: Unpack[_ClientOptions],
    ) -> None:
        core = AsyncLyraClient(
            host,
            options.get("timeout", 30.0),
            options.get("headers"),
            agent_api_key=options.get("agent_api_key"),
            secure=options.get("secure", True),
        )
        self._core = core
        self.health = core.health
        self.lookups = core.lookups
        self.catalog = core.catalog
        self.jobs = core.jobs
        self.results = core.results
        self.raw = core.raw
        verifier = AsyncCatalogVerifier(
            core,
            options.get("verify_catalog", "warn"),
        )
        self.metrics = AsyncMetrics(core, verifier)


__all__ = ["AsyncClient", "Client"]
