# Generated by lyra-client. Do not edit.
import os
from typing import cast

from lyra.api import (
    AsyncJobHandle,
    AsyncLyraClient,
    JobHandle,
    LyraClient,
    RunOptions,
    SubmitOptions,
)
from lyra.sdk import (
    BoundsReference,
    FileJobResult,
    LocationReference,
    TableJobResult,
)

from ._models import (
    AdvancedScoreRequest,
    AdvancedScoreRequestSectorsItem,
    AdvancedScoreScoringConfig,
    JobAccessibilityRequest,
    RasterExportRequest,
)
from ._runtime import (
    OMITTED,
    AsyncCatalogVerifier,
    CatalogVerifier,
    OmittedType,
    validate_metric_arguments,
)


class AdvancedScoreMetric:
    _metric_name = "advanced_score"

    def __init__(self, core: LyraClient, verifier: CatalogVerifier) -> None:
        self._core = core
        self._verifier = verifier

    def submit(
        self,
        *,
        config: AdvancedScoreScoringConfig,
        location: LocationReference,
        sectors: list[AdvancedScoreRequestSectorsItem],
        lyra_options: SubmitOptions | None = None,
    ) -> JobHandle[TableJobResult]:
        request_arguments: dict[str, object] = {}
        request_arguments["config"] = config
        request_arguments["location"] = location
        request_arguments["sectors"] = sectors
        request = AdvancedScoreRequest.model_validate(request_arguments)
        arguments = request.model_dump(mode="json", exclude_unset=True)
        validate_metric_arguments(self._metric_name, arguments)
        self._verifier.verify()
        return cast(
            "JobHandle[TableJobResult]",
            self._core.raw.submit(self._metric_name, arguments, options=lyra_options),
        )

    def run(
        self,
        *,
        config: AdvancedScoreScoringConfig,
        location: LocationReference,
        sectors: list[AdvancedScoreRequestSectorsItem],
        lyra_options: RunOptions | None = None,
    ) -> TableJobResult:
        request_arguments: dict[str, object] = {}
        request_arguments["config"] = config
        request_arguments["location"] = location
        request_arguments["sectors"] = sectors
        request = AdvancedScoreRequest.model_validate(request_arguments)
        arguments = request.model_dump(mode="json", exclude_unset=True)
        validate_metric_arguments(self._metric_name, arguments)
        self._verifier.verify()
        return cast(
            "TableJobResult",
            self._core.raw.run(self._metric_name, arguments, options=lyra_options),
        )


class AsyncAdvancedScoreMetric:
    _metric_name = "advanced_score"

    def __init__(self, core: AsyncLyraClient, verifier: AsyncCatalogVerifier) -> None:
        self._core = core
        self._verifier = verifier

    async def submit(
        self,
        *,
        config: AdvancedScoreScoringConfig,
        location: LocationReference,
        sectors: list[AdvancedScoreRequestSectorsItem],
        lyra_options: SubmitOptions | None = None,
    ) -> AsyncJobHandle[TableJobResult]:
        request_arguments: dict[str, object] = {}
        request_arguments["config"] = config
        request_arguments["location"] = location
        request_arguments["sectors"] = sectors
        request = AdvancedScoreRequest.model_validate(request_arguments)
        arguments = request.model_dump(mode="json", exclude_unset=True)
        validate_metric_arguments(self._metric_name, arguments)
        await self._verifier.verify()
        return cast(
            "AsyncJobHandle[TableJobResult]",
            await self._core.raw.submit(
                self._metric_name, arguments, options=lyra_options
            ),
        )

    async def run(
        self,
        *,
        config: AdvancedScoreScoringConfig,
        location: LocationReference,
        sectors: list[AdvancedScoreRequestSectorsItem],
        lyra_options: RunOptions | None = None,
    ) -> TableJobResult:
        request_arguments: dict[str, object] = {}
        request_arguments["config"] = config
        request_arguments["location"] = location
        request_arguments["sectors"] = sectors
        request = AdvancedScoreRequest.model_validate(request_arguments)
        arguments = request.model_dump(mode="json", exclude_unset=True)
        validate_metric_arguments(self._metric_name, arguments)
        await self._verifier.verify()
        return cast(
            "TableJobResult",
            await self._core.raw.run(
                self._metric_name, arguments, options=lyra_options
            ),
        )


class JobAccessibilityMetric:
    _metric_name = "job_accessibility"

    def __init__(self, core: LyraClient, verifier: CatalogVerifier) -> None:
        self._core = core
        self._verifier = verifier

    def submit(
        self,
        *,
        limit: int = 50,
        location: LocationReference,
        threshold: float | None = None,
        lyra_options: SubmitOptions | None = None,
    ) -> JobHandle[TableJobResult]:
        request_arguments: dict[str, object] = {}
        request_arguments["limit"] = limit
        request_arguments["location"] = location
        request_arguments["threshold"] = threshold
        request = JobAccessibilityRequest.model_validate(request_arguments)
        arguments = request.model_dump(mode="json", exclude_unset=True)
        validate_metric_arguments(self._metric_name, arguments)
        self._verifier.verify()
        return cast(
            "JobHandle[TableJobResult]",
            self._core.raw.submit(self._metric_name, arguments, options=lyra_options),
        )

    def run(
        self,
        *,
        limit: int = 50,
        location: LocationReference,
        threshold: float | None = None,
        lyra_options: RunOptions | None = None,
    ) -> TableJobResult:
        request_arguments: dict[str, object] = {}
        request_arguments["limit"] = limit
        request_arguments["location"] = location
        request_arguments["threshold"] = threshold
        request = JobAccessibilityRequest.model_validate(request_arguments)
        arguments = request.model_dump(mode="json", exclude_unset=True)
        validate_metric_arguments(self._metric_name, arguments)
        self._verifier.verify()
        return cast(
            "TableJobResult",
            self._core.raw.run(self._metric_name, arguments, options=lyra_options),
        )


class AsyncJobAccessibilityMetric:
    _metric_name = "job_accessibility"

    def __init__(self, core: AsyncLyraClient, verifier: AsyncCatalogVerifier) -> None:
        self._core = core
        self._verifier = verifier

    async def submit(
        self,
        *,
        limit: int = 50,
        location: LocationReference,
        threshold: float | None = None,
        lyra_options: SubmitOptions | None = None,
    ) -> AsyncJobHandle[TableJobResult]:
        request_arguments: dict[str, object] = {}
        request_arguments["limit"] = limit
        request_arguments["location"] = location
        request_arguments["threshold"] = threshold
        request = JobAccessibilityRequest.model_validate(request_arguments)
        arguments = request.model_dump(mode="json", exclude_unset=True)
        validate_metric_arguments(self._metric_name, arguments)
        await self._verifier.verify()
        return cast(
            "AsyncJobHandle[TableJobResult]",
            await self._core.raw.submit(
                self._metric_name, arguments, options=lyra_options
            ),
        )

    async def run(
        self,
        *,
        limit: int = 50,
        location: LocationReference,
        threshold: float | None = None,
        lyra_options: RunOptions | None = None,
    ) -> TableJobResult:
        request_arguments: dict[str, object] = {}
        request_arguments["limit"] = limit
        request_arguments["location"] = location
        request_arguments["threshold"] = threshold
        request = JobAccessibilityRequest.model_validate(request_arguments)
        arguments = request.model_dump(mode="json", exclude_unset=True)
        validate_metric_arguments(self._metric_name, arguments)
        await self._verifier.verify()
        return cast(
            "TableJobResult",
            await self._core.raw.run(
                self._metric_name, arguments, options=lyra_options
            ),
        )


class RasterExportMetric:
    _metric_name = "raster_export"

    def __init__(self, core: LyraClient, verifier: CatalogVerifier) -> None:
        self._core = core
        self._verifier = verifier

    def submit(
        self,
        *,
        bounds: BoundsReference,
        palette: list[str] | OmittedType = OMITTED,
        lyra_options: SubmitOptions | None = None,
    ) -> JobHandle[FileJobResult]:
        request_arguments: dict[str, object] = {}
        request_arguments["bounds"] = bounds
        if palette is not OMITTED:
            request_arguments["palette"] = palette
        request = RasterExportRequest.model_validate(request_arguments)
        arguments = request.model_dump(mode="json", exclude_unset=True)
        validate_metric_arguments(self._metric_name, arguments)
        self._verifier.verify()
        return cast(
            "JobHandle[FileJobResult]",
            self._core.raw.submit(self._metric_name, arguments, options=lyra_options),
        )

    def run(
        self,
        *,
        bounds: BoundsReference,
        palette: list[str] | OmittedType = OMITTED,
        lyra_options: RunOptions | None = None,
    ) -> FileJobResult:
        request_arguments: dict[str, object] = {}
        request_arguments["bounds"] = bounds
        if palette is not OMITTED:
            request_arguments["palette"] = palette
        request = RasterExportRequest.model_validate(request_arguments)
        arguments = request.model_dump(mode="json", exclude_unset=True)
        validate_metric_arguments(self._metric_name, arguments)
        self._verifier.verify()
        return cast(
            "FileJobResult",
            self._core.raw.run(self._metric_name, arguments, options=lyra_options),
        )

    def run_to_file(
        self,
        *,
        path: str | os.PathLike[str],
        bounds: BoundsReference,
        palette: list[str] | OmittedType = OMITTED,
        lyra_options: RunOptions | None = None,
    ) -> None:
        request_arguments: dict[str, object] = {}
        request_arguments["bounds"] = bounds
        if palette is not OMITTED:
            request_arguments["palette"] = palette
        request = RasterExportRequest.model_validate(request_arguments)
        arguments = request.model_dump(mode="json", exclude_unset=True)
        validate_metric_arguments(self._metric_name, arguments)
        self._verifier.verify()
        self._core.raw.run_to_file(
            self._metric_name,
            arguments,
            path,
            options=lyra_options,
        )


class AsyncRasterExportMetric:
    _metric_name = "raster_export"

    def __init__(self, core: AsyncLyraClient, verifier: AsyncCatalogVerifier) -> None:
        self._core = core
        self._verifier = verifier

    async def submit(
        self,
        *,
        bounds: BoundsReference,
        palette: list[str] | OmittedType = OMITTED,
        lyra_options: SubmitOptions | None = None,
    ) -> AsyncJobHandle[FileJobResult]:
        request_arguments: dict[str, object] = {}
        request_arguments["bounds"] = bounds
        if palette is not OMITTED:
            request_arguments["palette"] = palette
        request = RasterExportRequest.model_validate(request_arguments)
        arguments = request.model_dump(mode="json", exclude_unset=True)
        validate_metric_arguments(self._metric_name, arguments)
        await self._verifier.verify()
        return cast(
            "AsyncJobHandle[FileJobResult]",
            await self._core.raw.submit(
                self._metric_name, arguments, options=lyra_options
            ),
        )

    async def run(
        self,
        *,
        bounds: BoundsReference,
        palette: list[str] | OmittedType = OMITTED,
        lyra_options: RunOptions | None = None,
    ) -> FileJobResult:
        request_arguments: dict[str, object] = {}
        request_arguments["bounds"] = bounds
        if palette is not OMITTED:
            request_arguments["palette"] = palette
        request = RasterExportRequest.model_validate(request_arguments)
        arguments = request.model_dump(mode="json", exclude_unset=True)
        validate_metric_arguments(self._metric_name, arguments)
        await self._verifier.verify()
        return cast(
            "FileJobResult",
            await self._core.raw.run(
                self._metric_name, arguments, options=lyra_options
            ),
        )

    async def run_to_file(
        self,
        *,
        path: str | os.PathLike[str],
        bounds: BoundsReference,
        palette: list[str] | OmittedType = OMITTED,
        lyra_options: RunOptions | None = None,
    ) -> None:
        request_arguments: dict[str, object] = {}
        request_arguments["bounds"] = bounds
        if palette is not OMITTED:
            request_arguments["palette"] = palette
        request = RasterExportRequest.model_validate(request_arguments)
        arguments = request.model_dump(mode="json", exclude_unset=True)
        validate_metric_arguments(self._metric_name, arguments)
        await self._verifier.verify()
        await self._core.raw.run_to_file(
            self._metric_name,
            arguments,
            path,
            options=lyra_options,
        )


class Metrics:
    def __init__(self, core: LyraClient, verifier: CatalogVerifier) -> None:
        self.advanced_score = AdvancedScoreMetric(core, verifier)
        self.job_accessibility = JobAccessibilityMetric(core, verifier)
        self.raster_export = RasterExportMetric(core, verifier)


class AsyncMetrics:
    def __init__(self, core: AsyncLyraClient, verifier: AsyncCatalogVerifier) -> None:
        self.advanced_score = AsyncAdvancedScoreMetric(core, verifier)
        self.job_accessibility = AsyncJobAccessibilityMetric(core, verifier)
        self.raster_export = AsyncRasterExportMetric(core, verifier)


__all__ = [
    "AdvancedScoreMetric",
    "AsyncAdvancedScoreMetric",
    "AsyncJobAccessibilityMetric",
    "AsyncMetrics",
    "AsyncRasterExportMetric",
    "JobAccessibilityMetric",
    "Metrics",
    "RasterExportMetric",
]
