# Generated by lyra-client. Do not edit.
import json
from enum import StrEnum
from typing import cast

from lyra.sdk import (
    BoundsReference,
    LocationReference,
)
from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
)

from ._runtime import OMITTED


class _GeneratedModel(BaseModel):
    model_config = ConfigDict(extra="forbid", strict=True)


class AdvancedScoreScoringConfigModeEnum(StrEnum):
    FAST = "fast"
    PRECISE = "precise"


class AdvancedScoreRequestSectorsItem(_GeneratedModel):
    key: str
    label: str = cast("str", OMITTED)
    value: str


class AdvancedScoreScoringConfig(_GeneratedModel):
    mode: AdvancedScoreScoringConfigModeEnum
    weights: dict[str, float] = Field(
        default_factory=lambda: json.loads(r"""{"distance": 1.0}"""),
    )


class AdvancedScoreRequest(_GeneratedModel):
    config: AdvancedScoreScoringConfig
    location: LocationReference
    sectors: list[AdvancedScoreRequestSectorsItem]


class JobAccessibilityRequest(_GeneratedModel):
    limit: int = 50
    location: LocationReference
    threshold: float | None = None


class RasterExportRequest(_GeneratedModel):
    bounds: BoundsReference
    palette: list[str] = Field(
        default_factory=lambda: json.loads(r"""["#000000", "#ffffff"]"""),
    )
