# Generated by lyra-client. Do not edit.
from __future__ import annotations

import json
import warnings
from typing import TYPE_CHECKING, Literal

from jsonschema import Draft202012Validator
from lyra.api import AsyncLyraClient, LyraAPIError, LyraClient

from ._contract import (
    CATALOG_FINGERPRINT,
    CLIENT_SCHEMA_VERSION,
    JSON_SCHEMA_DIALECT,
)

if TYPE_CHECKING:
    from lyra.sdk.types import JsonObject


class OmittedType:
    __slots__ = ()

    def __repr__(self) -> str:
        return "OMITTED"


OMITTED = OmittedType()
_SCHEMAS: dict[str, JsonObject] = json.loads(r"""{
  "advanced_score": {
    "$defs": {
      "ScoringConfig": {
        "additionalProperties": false,
        "properties": {
          "mode": {
            "enum": [
              "fast",
              "precise"
            ],
            "type": "string"
          },
          "weights": {
            "additionalProperties": {
              "type": "number"
            },
            "default": {
              "distance": 1.0
            },
            "type": "object"
          }
        },
        "required": [
          "mode"
        ],
        "type": "object"
      }
    },
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "additionalProperties": false,
    "properties": {
      "config": {
        "$ref": "#/$defs/ScoringConfig"
      },
      "location": {
        "type": "object"
      },
      "sectors": {
        "items": {
          "additionalProperties": false,
          "properties": {
            "key": {
              "pattern": "^[a-z][a-z0-9_]*$",
              "type": "string"
            },
            "label": {
              "type": "string"
            },
            "value": {
              "type": "string"
            }
          },
          "required": [
            "key",
            "value"
          ],
          "type": "object"
        },
        "maxItems": 10,
        "minItems": 1,
        "type": "array"
      }
    },
    "required": [
      "location",
      "config",
      "sectors"
    ],
    "type": "object"
  },
  "job_accessibility": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "additionalProperties": false,
    "properties": {
      "limit": {
        "default": 50,
        "minimum": 1,
        "type": "integer"
      },
      "location": {
        "oneOf": [
          {
            "additionalProperties": false,
            "properties": {
              "data_type": {
                "const": "cvegeo_list"
              },
              "value": {
                "items": {
                  "type": "string"
                },
                "type": "array"
              }
            },
            "required": [
              "value"
            ],
            "type": "object"
          },
          {
            "additionalProperties": false,
            "properties": {
              "data_type": {
                "const": "met_zone_code"
              },
              "value": {
                "type": "string"
              }
            },
            "required": [
              "value"
            ],
            "type": "object"
          }
        ]
      },
      "threshold": {
        "anyOf": [
          {
            "type": "number"
          },
          {
            "type": "null"
          }
        ],
        "default": null
      }
    },
    "required": [
      "location"
    ],
    "type": "object"
  },
  "raster_export": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "additionalProperties": false,
    "properties": {
      "bounds": {
        "type": "object"
      },
      "palette": {
        "default": [
          "#000000",
          "#ffffff"
        ],
        "items": {
          "type": "string"
        },
        "type": "array"
      }
    },
    "required": [
      "bounds"
    ],
    "type": "object"
  }
}""")


class MetricArgumentsError(ValueError):
    pass


class CatalogCompatibilityWarning(UserWarning):
    pass


class CatalogCompatibilityError(RuntimeError):
    pass


def validate_metric_arguments(metric: str, arguments: JsonObject) -> None:
    errors = sorted(
        Draft202012Validator(_SCHEMAS[metric]).iter_errors(arguments),
        key=lambda error: list(error.path),
    )
    if errors:
        details = "; ".join(
            f"{'.'.join(str(item) for item in error.path) or '<root>'}: {error.message}"
            for error in errors
        )
        message = f"Invalid arguments for {metric}: {details}"
        raise MetricArgumentsError(message)


class CatalogVerifier:
    def __init__(
        self,
        core: LyraClient,
        mode: Literal["off", "warn", "error"],
    ) -> None:
        if mode not in {"off", "warn", "error"}:
            message = "verify_catalog must be 'off', 'warn', or 'error'"
            raise ValueError(message)
        self._core = core
        self._mode = mode
        self._verified = mode == "off"

    def verify(self) -> None:
        if self._verified:
            return
        self._verified = True
        try:
            catalog = self._core.catalog.metrics()
            compatible = (
                catalog.client_schema_version == CLIENT_SCHEMA_VERSION
                and catalog.json_schema_dialect == JSON_SCHEMA_DIALECT
                and catalog.catalog_fingerprint == CATALOG_FINGERPRINT
            )
            detail = "server catalog does not match the generated client contract"
        except (LyraAPIError, RuntimeError, ValueError) as exc:
            compatible = False
            detail = f"could not verify the server catalog: {exc}"
        if compatible:
            return
        if self._mode == "error":
            raise CatalogCompatibilityError(detail)
        warnings.warn(detail, CatalogCompatibilityWarning, stacklevel=3)


class AsyncCatalogVerifier:
    def __init__(
        self,
        core: AsyncLyraClient,
        mode: Literal["off", "warn", "error"],
    ) -> None:
        if mode not in {"off", "warn", "error"}:
            message = "verify_catalog must be 'off', 'warn', or 'error'"
            raise ValueError(message)
        self._core = core
        self._mode = mode
        self._verified = mode == "off"

    async def verify(self) -> None:
        if self._verified:
            return
        self._verified = True
        try:
            catalog = await self._core.catalog.metrics()
            compatible = (
                catalog.client_schema_version == CLIENT_SCHEMA_VERSION
                and catalog.json_schema_dialect == JSON_SCHEMA_DIALECT
                and catalog.catalog_fingerprint == CATALOG_FINGERPRINT
            )
            detail = "server catalog does not match the generated client contract"
        except (LyraAPIError, RuntimeError, ValueError) as exc:
            compatible = False
            detail = f"could not verify the server catalog: {exc}"
        if compatible:
            return
        if self._mode == "error":
            raise CatalogCompatibilityError(detail)
        warnings.warn(detail, CatalogCompatibilityWarning, stacklevel=3)
