services:
  lyra-dev:
    image: lyra-dev:latest
    container_name: lyra-dev
    restart: unless-stopped
    ports:
      - 5219:5219
    volumes:
      - ${SERVICE_ACCOUNT_BIND_PATH}:/app/service-account.json:ro
      - ${LYRA_CACHE_BIND_PATH}:/lyra_cache
      - lyra_plugin_catalog:/lyra_plugin_catalog
    networks:
      - lyra_net
    environment:
      - CELERY_BROKER_URL=redis://lyra-redis-dev:6379/0
    env_file:
      - ../.env
    build: ..
    develop:
      watch:
        - action: sync+restart
          path: ..
          target: /app
          ignore:
            - .git/
            - __pycache__/
            - .venv/
            - venv/
            - "*.env"
            - "*.ipynb"

  lyra-redis-dev:
    image: redis:alpine
    container_name: lyra-redis-dev
    restart: unless-stopped
    networks:
      - lyra_net

  lyra-celery-worker-lightweight-dev:
    image: lyra-dev:latest
    container_name: lyra-celery-worker-lightweight-dev
    restart: unless-stopped
    command: celery -A lyra_app.worker.celery_app worker --loglevel=info --concurrency=${CELERY_WORKER_CONCURRENCY:-32} -Q lightweight
    environment:
      - LYRA_RUNNER_QUEUES=lightweight
      - CELERY_BROKER_URL=redis://lyra-redis-dev:6379/0
    volumes:
      - ${SERVICE_ACCOUNT_BIND_PATH}:/app/service-account.json:ro
      - ${LYRA_CACHE_BIND_PATH}:/lyra_cache
      - lyra_plugins_lightweight:/lyra_plugins
    networks:
      - lyra_net
    depends_on:
      - lyra-redis-dev
      - lyra-dev
    env_file:
      - ../.env
    build: ..
    develop:
      watch:
        - action: sync+restart
          path: ..
          target: /app
          ignore:
            - .git/
            - __pycache__/
            - .venv/
            - venv/
            - "*.env"
            - "*.ipynb"

  lyra-celery-worker-earth-engine-dev:
    image: lyra-dev:latest
    container_name: lyra-celery-worker-earth-engine-dev
    restart: unless-stopped
    command: celery -A lyra_app.worker.celery_app worker --loglevel=info --concurrency=${CELERY_WORKER_CONCURRENCY:-32} -Q earth_engine
    environment:
      - LYRA_RUNNER_QUEUES=earth_engine
      - CELERY_BROKER_URL=redis://lyra-redis-dev:6379/0
    volumes:
      - ${SERVICE_ACCOUNT_BIND_PATH}:/app/service-account.json:ro
      - ${LYRA_CACHE_BIND_PATH}:/lyra_cache
      - lyra_plugins_earth_engine:/lyra_plugins
    networks:
      - lyra_net
    depends_on:
      - lyra-redis-dev
      - lyra-dev
    env_file:
      - ../.env
    build: ..
    develop:
      watch:
        - action: sync+restart
          path: ..
          target: /app
          ignore:
            - .git/
            - __pycache__/
            - .venv/
            - venv/
            - "*.env"
            - "*.ipynb"

  lyra-celery-worker-heavy-dev:
    image: lyra-dev:latest
    container_name: lyra-celery-worker-heavy-dev
    restart: unless-stopped
    command: celery -A lyra_app.worker.celery_app worker --loglevel=info --concurrency=${CELERY_WORKER_CONCURRENCY:-32} -Q heavy
    environment:
      - LYRA_RUNNER_QUEUES=heavy
      - CELERY_BROKER_URL=redis://lyra-redis-dev:6379/0
    volumes:
      - ${SERVICE_ACCOUNT_BIND_PATH}:/app/service-account.json:ro
      - ${LYRA_CACHE_BIND_PATH}:/lyra_cache
      - lyra_plugins_heavy:/lyra_plugins
    networks:
      - lyra_net
    depends_on:
      - lyra-redis-dev
      - lyra-dev
    env_file:
      - ../.env
    build: ..
    develop:
      watch:
        - action: sync+restart
          path: ..
          target: /app
          ignore:
            - .git/
            - __pycache__/
            - .venv/
            - venv/
            - "*.env"
            - "*.ipynb"
networks:
  lyra_net:
    name: lyra_net
    driver: bridge

volumes:
  lyra_plugin_catalog:
    name: lyra_plugin_catalog
  lyra_plugins_lightweight:
    name: lyra_plugins_lightweight
  lyra_plugins_earth_engine:
    name: lyra_plugins_earth_engine
  lyra_plugins_heavy:
    name: lyra_plugins_heavy
