services:
  lyra:
    image: lyra:latest
    restart: unless-stopped
    ports:
      - 5219:5219
    volumes:
      - ${SERVICE_ACCOUNT_BIND_PATH}:/app/service-account.json
    env_file:
      - ../.env
    build: ..
    develop:
      watch:
        - action: sync+restart
          path: ..
          target: /app
          ignore:
            - .git/
            - __pycache__/
            - .venv/
            - venv/
            - "*.env"
            - "*.ipynb"
        

  redis:
    image: redis:alpine
    restart: unless-stopped


  celery_worker:
    image: lyra:latest
    command: uv run --no-dev --frozen celery -A lyra.worker.celery_app worker --loglevel=info
    volumes:
      - ${SERVICE_ACCOUNT_BIND_PATH}:/app/service-account.json
    depends_on:
      - redis
    env_file:
      - ../.env
    build: ..
    develop:
      watch:
        - action: sync+restart
          path: ..
          target: /app
          ignore:
            - .git/
            - __pycache__/
            - .venv/
            - venv/
            - "*.env"
            - "*.ipynb"
networks:
  lyra_net:
    name: lyra_net
    driver: bridge