from __future__ import annotations

import argparse
import ast
import difflib
import importlib.metadata
import importlib.util
import json
import re
import sys
import tempfile
import warnings
from dataclasses import dataclass, field
from pathlib import Path

import requests
from jsonschema import Draft202012Validator
from jsonschema.exceptions import SchemaError
from lyra.sdk.client_contract import CLIENT_SCHEMA_VERSION, JSON_SCHEMA_DIALECT
from lyra.sdk.models.metric import MetricCatalogResponse, MetricInfoV4
from lyra.sdk.types import JsonObject, JsonValue, validate_json_object

GENERATED_HEADER = "# Generated by lyra-client. Do not edit.\n"
MANIFEST_NAME = ".lyra-client-manifest.json"
_PUBLIC_NAME = re.compile(r"^[a-z][a-z0-9_]*$")
_PACKAGE_NAME = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


class ClientGenerationError(ValueError):
    """Raised when a catalog cannot be emitted safely."""


class ClientGenerationWarning(UserWarning):
    """A valid schema construct required a conservative generated annotation."""


def _generator_version() -> str:
    try:
        return importlib.metadata.version("lyra-api")
    except importlib.metadata.PackageNotFoundError:
        return "0+unknown"


def _pascal(value: str) -> str:
    parts = [part for part in re.split(r"[^A-Za-z0-9]+", value) if part]
    result = "".join(part[:1].upper() + part[1:] for part in parts)
    if not result or result[0].isdigit():
        result = f"Value{result}"
    return result


def _enum_member(value: str, index: int) -> str:
    member = re.sub(r"[^A-Za-z0-9]+", "_", value).strip("_").upper()
    if not member or member[0].isdigit():
        member = f"VALUE_{member or index}"
    return member


def _literal(value: JsonValue) -> str:
    if isinstance(value, str):
        return json.dumps(value, ensure_ascii=False)
    return repr(value)


def _default_expression(field_spec: _FieldSpec) -> str:
    if isinstance(field_spec.default, str) and field_spec.annotation.endswith("Enum"):
        return f"{field_spec.annotation}.{_enum_member(field_spec.default, 0)}"
    return _literal(field_spec.default)


def _complex_default_expression(value: JsonValue) -> str:
    payload = json.dumps(value, sort_keys=True, ensure_ascii=False)
    return f'json.loads(r"""{payload}""")'


def _all_block(values: list[str]) -> str:
    return "__all__ = [\n" + "".join(f'    "{value}",\n' for value in values) + "]"


def _import_block(module: str, names: list[str]) -> list[str]:
    return [f"from {module} import (", *[f"    {name}," for name in names], ")"]


def canonical_catalog_json(catalog: MetricCatalogResponse) -> str:
    """Serialize a catalog snapshot deterministically."""

    payload = catalog.model_dump(mode="json")
    payload["metrics"] = sorted(payload["metrics"], key=lambda item: item["name"])
    return json.dumps(payload, indent=2, sort_keys=True, ensure_ascii=False) + "\n"


def pull_catalog(host: str, *, insecure: bool = False) -> MetricCatalogResponse:
    """Fetch and validate the public generated-client catalog."""

    normalized = host.rstrip("/")
    if not normalized.startswith(("http://", "https://")):
        scheme = "http" if insecure else "https"
        normalized = f"{scheme}://{normalized}"
    response = requests.get(f"{normalized}/metrics", timeout=30)
    response.raise_for_status()
    return MetricCatalogResponse.model_validate(response.json())


@dataclass
class _FieldSpec:
    name: str
    annotation: str
    required: bool
    has_default: bool
    default: JsonValue = None

    @property
    def uses_omission(self) -> bool:
        return not self.required and (
            not self.has_default or isinstance(self.default, list | dict)
        )


@dataclass
class _ModelSpec:
    name: str
    fields: list[_FieldSpec] = field(default_factory=list)


@dataclass
class _EnumSpec:
    name: str
    values: list[str]


class _SchemaEmitter:
    def __init__(self, metric: MetricInfoV4) -> None:
        self.metric = metric
        self.root = metric.request_schema
        self.prefix = _pascal(metric.name)
        self.models: dict[str, _ModelSpec] = {}
        self.enums: dict[str, _EnumSpec] = {}
        self.names: dict[str, str] = {}
        self.warnings: list[str] = []

    def _claim(self, name: str, source: str) -> None:
        identity = name.casefold()
        previous = self.names.get(identity)
        if previous is not None and previous != source:
            msg = f"generated name collision for {name}: {previous} and {source}"
            raise ClientGenerationError(msg)
        self.names[identity] = source

    def _fallback(self, path: str, reason: str) -> str:
        message = f"{self.metric.name}:{path}: {reason}; using JsonValue"
        if message not in self.warnings:
            self.warnings.append(message)
        return "JsonValue"

    def _resolve_ref(self, reference: str) -> JsonObject:
        if not reference.startswith("#/"):
            msg = f"{self.metric.name}: external reference is unsupported: {reference}"
            raise ClientGenerationError(msg)
        value: object = self.root
        for raw_part in reference[2:].split("/"):
            part = raw_part.replace("~1", "/").replace("~0", "~")
            if not isinstance(value, dict) or part not in value:
                msg = f"{self.metric.name}: broken reference: {reference}"
                raise ClientGenerationError(msg)
            value = value[part]
        if not isinstance(value, dict):
            msg = f"{self.metric.name}: reference does not target a schema: {reference}"
            raise ClientGenerationError(msg)
        return validate_json_object(value)

    def annotation(
        self,
        schema: JsonObject,
        hint: str,
        path: str,
        *,
        spatial_kind: str | None = None,
    ) -> str:
        spatial_annotations = {
            "location": "LocationReference",
            "bounds": "BoundsReference",
        }
        if spatial_kind in spatial_annotations:
            return spatial_annotations[spatial_kind]
        reference = schema.get("$ref")
        if isinstance(reference, str):
            target = self._resolve_ref(reference)
            name = f"{self.prefix}{_pascal(reference.rsplit('/', maxsplit=1)[-1])}"
            return self.annotation(target, name, f"{path}.$ref")
        if "const" in schema:
            return f"Literal[{_literal(schema['const'])}]"
        enum = schema.get("enum")
        if isinstance(enum, list) and enum:
            return self._enum_annotation(enum, hint, path)
        union = self._union_annotation(schema, hint, path)
        if union is not None:
            return union
        return self._type_annotation(schema, hint, path)

    def _enum_annotation(self, enum: list[JsonValue], hint: str, path: str) -> str:
        if not all(isinstance(item, str) for item in enum):
            return "Literal[" + ", ".join(_literal(item) for item in enum) + "]"
        name = hint if hint.endswith("Enum") else f"{hint}Enum"
        self._claim(name, path)
        values = [str(item) for item in enum]
        members = [_enum_member(value, index) for index, value in enumerate(values)]
        if len(set(members)) != len(members):
            return "Literal[" + ", ".join(_literal(item) for item in values) + "]"
        self.enums.setdefault(name, _EnumSpec(name, values))
        return name

    def _union_annotation(
        self,
        schema: JsonObject,
        hint: str,
        path: str,
    ) -> str | None:
        for union_key in ("anyOf", "oneOf"):
            variants = schema.get(union_key)
            if isinstance(variants, list) and variants:
                annotations = [
                    self.annotation(
                        validate_json_object(variant),
                        f"{hint}Variant{index + 1}",
                        f"{path}.{union_key}[{index}]",
                    )
                    for index, variant in enumerate(variants)
                    if isinstance(variant, dict)
                ]
                if len(annotations) != len(variants):
                    return self._fallback(path, f"non-object {union_key} branch")
                return " | ".join(dict.fromkeys(annotations))
        schema_type = schema.get("type")
        if not isinstance(schema_type, list):
            return None
        annotations = [
            self.annotation(
                {**schema, "type": item},
                f"{hint}Variant{index + 1}",
                f"{path}.type[{index}]",
            )
            for index, item in enumerate(schema_type)
            if isinstance(item, str)
        ]
        return " | ".join(dict.fromkeys(annotations))

    def _type_annotation(self, schema: JsonObject, hint: str, path: str) -> str:
        schema_type = schema.get("type")
        primitive_types = {
            "null": "None",
            "string": "str",
            "integer": "int",
            "number": "float",
            "boolean": "bool",
        }
        if isinstance(schema_type, str) and schema_type in primitive_types:
            return primitive_types[schema_type]
        if schema_type == "array":
            return self._array_annotation(schema, hint, path)
        if schema_type == "object" or isinstance(schema.get("properties"), dict):
            return self._object_annotation(schema, hint, path)
        return self._fallback(path, "unsupported valid JSON Schema construct")

    def _array_annotation(self, schema: JsonObject, hint: str, path: str) -> str:
        items = schema.get("items")
        if not isinstance(items, dict):
            return self._fallback(path, "array items are not a single schema")
        item_annotation = self.annotation(
            validate_json_object(items),
            f"{hint}Item",
            f"{path}.items",
        )
        return f"list[{item_annotation}]"

    def _object_annotation(self, schema: JsonObject, hint: str, path: str) -> str:
        if isinstance(schema.get("properties"), dict):
            return self.object_model(schema, hint, path)
        additional = schema.get("additionalProperties")
        if not isinstance(additional, dict):
            return "dict[str, JsonValue]"
        value_annotation = self.annotation(
            validate_json_object(additional),
            f"{hint}Value",
            f"{path}.additionalProperties",
        )
        return f"dict[str, {value_annotation}]"

    def object_model(self, schema: JsonObject, name: str, path: str) -> str:
        self._claim(name, path)
        if name in self.models:
            return name
        model = _ModelSpec(name)
        self.models[name] = model
        properties = schema.get("properties", {})
        required_value = schema.get("required", [])
        required = set(required_value) if isinstance(required_value, list) else set()
        if not isinstance(properties, dict):
            return self._fallback(path, "object properties are not an object")
        for field_name, raw_schema in properties.items():
            if not isinstance(field_name, str) or not _PUBLIC_NAME.fullmatch(
                field_name
            ):
                msg = (
                    f"{self.metric.name}:{path}: unemittable field name {field_name!r}"
                )
                raise ClientGenerationError(msg)
            if field_name.startswith("lyra_"):
                msg = f"{self.metric.name}:{path}: reserved field name {field_name!r}"
                raise ClientGenerationError(msg)
            if not isinstance(raw_schema, dict):
                annotation = self._fallback(f"{path}.{field_name}", "boolean schema")
                property_schema: JsonObject = {}
            else:
                property_schema = validate_json_object(raw_schema)
                annotation = self.annotation(
                    property_schema,
                    f"{name}{_pascal(field_name)}",
                    f"{path}.properties.{field_name}",
                    spatial_kind=self.metric.spatial_inputs.get(field_name),
                )
            model.fields.append(
                _FieldSpec(
                    name=field_name,
                    annotation=annotation,
                    required=field_name in required,
                    has_default="default" in property_schema,
                    default=property_schema.get("default"),
                )
            )
        return name

    def emit(self) -> tuple[str, list[_FieldSpec], list[str]]:
        request_name = f"{self.prefix}Request"
        self.object_model(self.root, request_name, "$request")
        lines = [
            GENERATED_HEADER.rstrip(),
            "from __future__ import annotations",
            "",
            "from enum import StrEnum",
            "from typing import Literal, cast",
            "",
            "from lyra.sdk import BoundsReference, LocationReference",
            "from lyra.sdk.types import JsonValue",
            "from pydantic import BaseModel, ConfigDict, Field",
            "",
            "from ._runtime import OMITTED",
            "",
            "",
            "class _GeneratedModel(BaseModel):",
            '    model_config = ConfigDict(extra="forbid", strict=True)',
        ]
        for enum_spec in self.enums.values():
            lines.extend(["", "", f"class {enum_spec.name}(StrEnum):"])
            for index, value in enumerate(enum_spec.values):
                lines.append(f"    {_enum_member(value, index)} = {_literal(value)}")
        for model_spec in reversed(self.models.values()):
            lines.extend(["", "", f"class {model_spec.name}(_GeneratedModel):"])
            if not model_spec.fields:
                lines.append("    pass")
            for field_spec in model_spec.fields:
                if field_spec.required:
                    suffix = ""
                elif field_spec.has_default and isinstance(
                    field_spec.default, list | dict
                ):
                    default = _complex_default_expression(field_spec.default)
                    lines.extend(
                        [
                            f"    {field_spec.name}: {field_spec.annotation} = Field(",
                            f"        default_factory=lambda: {default},",
                            "    )",
                        ]
                    )
                    continue
                elif field_spec.has_default:
                    suffix = f" = {_default_expression(field_spec)}"
                else:
                    suffix = f' = cast("{field_spec.annotation}", OMITTED)'
                lines.append(f"    {field_spec.name}: {field_spec.annotation}{suffix}")
        lines.extend(["", ""])
        exported = [*self.enums, *self.models]
        lines.append(_all_block(sorted(exported)))
        request_fields = self.models[request_name].fields
        return "\n".join(lines) + "\n", request_fields, self.warnings


def _method_parameters(fields: list[_FieldSpec], options_type: str) -> list[str]:
    parameters: list[str] = []
    for field_spec in fields:
        if field_spec.required:
            default = ""
            annotation = field_spec.annotation
        elif field_spec.uses_omission:
            default = " = OMITTED"
            annotation = f"{field_spec.annotation} | OmittedType"
        else:
            default = f" = {_default_expression(field_spec)}"
            annotation = field_spec.annotation
        parameters.append(f"        {field_spec.name}: {annotation}{default},")
    parameters.append(f"        lyra_options: {options_type} | None = None,")
    return parameters


def _arguments_body(request_name: str, fields: list[_FieldSpec]) -> list[str]:
    lines = ["        request_arguments: dict[str, object] = {}"]
    for field_spec in fields:
        if field_spec.uses_omission:
            lines.extend(
                [
                    f"        if {field_spec.name} is not OMITTED:",
                    (
                        f"            request_arguments[{_literal(field_spec.name)}] = "
                        f"{field_spec.name}"
                    ),
                ]
            )
        else:
            lines.append(
                f"        request_arguments[{_literal(field_spec.name)}] = "
                f"{field_spec.name}"
            )
    lines.extend(
        [
            f"        request = {request_name}.model_validate(request_arguments)",
            '        arguments = request.model_dump(mode="json", exclude_unset=True)',
            "        validate_metric_arguments(self._metric_name, arguments)",
        ]
    )
    return lines


def _render_metric_class(
    metric: MetricInfoV4,
    fields: list[_FieldSpec],
    *,
    async_: bool,
) -> str:
    prefix = _pascal(metric.name)
    request_name = f"{prefix}Request"
    class_name = f"{'Async' if async_ else ''}{prefix}Metric"
    handle = "AsyncJobHandle" if async_ else "JobHandle"
    result = "TableJobResult" if metric.output.kind == "table" else "FileJobResult"
    await_prefix = "await " if async_ else ""
    core_type = "AsyncLyraClient" if async_ else "LyraClient"
    verifier_type = "AsyncCatalogVerifier" if async_ else "CatalogVerifier"
    init_signature = (
        f"    def __init__(self, core: {core_type}, verifier: {verifier_type}) -> None:"
    )
    if async_:
        submit_call = [
            "            await self._core.raw.submit(",
            "                self._metric_name, arguments, options=lyra_options",
            "            ),",
        ]
        run_call = [
            "            await self._core.raw.run(",
            "                self._metric_name, arguments, options=lyra_options",
            "            ),",
        ]
    else:
        submit_call = [
            "            self._core.raw.submit("
            "self._metric_name, arguments, options=lyra_options),"
        ]
        run_call = [
            "            self._core.raw.run("
            "self._metric_name, arguments, options=lyra_options),"
        ]
    lines = [
        f"class {class_name}:",
        f"    _metric_name = {_literal(metric.name)}",
        "",
        init_signature,
        "        self._core = core",
        "        self._verifier = verifier",
        "",
        f"    {'async ' if async_ else ''}def submit(",
        "        self,",
        "        *,",
        *_method_parameters(fields, "SubmitOptions"),
        f"    ) -> {handle}[{result}]:",
        *_arguments_body(request_name, fields),
        f"        {await_prefix}self._verifier.verify()",
        "        return cast(",
        f'            "{handle}[{result}]",',
        *submit_call,
        "        )",
        "",
        f"    {'async ' if async_ else ''}def run(",
        "        self,",
        "        *,",
        *_method_parameters(fields, "RunOptions"),
        f"    ) -> {result}:",
        *_arguments_body(request_name, fields),
        f"        {await_prefix}self._verifier.verify()",
        "        return cast(",
        f'            "{result}",',
        *run_call,
        "        )",
    ]
    if metric.output.kind == "file":
        file_parameters = _method_parameters(fields, "RunOptions")
        lines.extend(
            [
                "",
                f"    {'async ' if async_ else ''}def run_to_file(",
                "        self,",
                "        *,",
                "        path: str | os.PathLike[str],",
                *file_parameters,
                "    ) -> None:",
                *_arguments_body(request_name, fields),
                f"        {await_prefix}self._verifier.verify()",
                f"        {await_prefix}self._core.raw.run_to_file(",
                "            self._metric_name,",
                "            arguments,",
                "            path,",
                "            options=lyra_options,",
                "        )",
            ]
        )
    return "\n".join(lines)


def _render_runtime(catalog: MetricCatalogResponse) -> str:
    schemas = {
        metric.name: metric.request_schema
        for metric in sorted(catalog.metrics, key=lambda m: m.name)
    }
    schemas_json = json.dumps(schemas, indent=2, sort_keys=True, ensure_ascii=False)
    validation_detail_line = (
        "            f\"{'.'.join(str(item) for item in error.path) "
        "or '<root>'}: {error.message}\""
    )
    return (
        GENERATED_HEADER
        + f"""from __future__ import annotations

import json
import warnings
from typing import TYPE_CHECKING, Literal

from jsonschema import Draft202012Validator
from lyra.api import AsyncLyraClient, LyraAPIError, LyraClient

from ._contract import (
    CATALOG_FINGERPRINT,
    CLIENT_SCHEMA_VERSION,
    JSON_SCHEMA_DIALECT,
)

if TYPE_CHECKING:
    from lyra.sdk.types import JsonObject


class OmittedType:
    __slots__ = ()

    def __repr__(self) -> str:
        return "OMITTED"


OMITTED = OmittedType()
_SCHEMAS: dict[str, JsonObject] = json.loads(r\"\"\"{schemas_json}\"\"\")


class MetricArgumentsError(ValueError):
    pass


class CatalogCompatibilityWarning(UserWarning):
    pass


class CatalogCompatibilityError(RuntimeError):
    pass


def validate_metric_arguments(metric: str, arguments: JsonObject) -> None:
    errors = sorted(
        Draft202012Validator(_SCHEMAS[metric]).iter_errors(arguments),
        key=lambda error: list(error.path),
    )
    if errors:
        details = "; ".join(
{validation_detail_line}
            for error in errors
        )
        message = f"Invalid arguments for {{metric}}: {{details}}"
        raise MetricArgumentsError(message)


class CatalogVerifier:
    def __init__(
        self,
        core: LyraClient,
        mode: Literal["off", "warn", "error"],
    ) -> None:
        if mode not in {{"off", "warn", "error"}}:
            message = "verify_catalog must be 'off', 'warn', or 'error'"
            raise ValueError(message)
        self._core = core
        self._mode = mode
        self._verified = mode == "off"

    def verify(self) -> None:
        if self._verified:
            return
        self._verified = True
        try:
            catalog = self._core.catalog.metrics()
            compatible = (
                catalog.client_schema_version == CLIENT_SCHEMA_VERSION
                and catalog.json_schema_dialect == JSON_SCHEMA_DIALECT
                and catalog.catalog_fingerprint == CATALOG_FINGERPRINT
            )
            detail = "server catalog does not match the generated client contract"
        except (LyraAPIError, RuntimeError, ValueError) as exc:
            compatible = False
            detail = f"could not verify the server catalog: {{exc}}"
        if compatible:
            return
        if self._mode == "error":
            raise CatalogCompatibilityError(detail)
        warnings.warn(detail, CatalogCompatibilityWarning, stacklevel=3)


class AsyncCatalogVerifier:
    def __init__(
        self,
        core: AsyncLyraClient,
        mode: Literal["off", "warn", "error"],
    ) -> None:
        if mode not in {{"off", "warn", "error"}}:
            message = "verify_catalog must be 'off', 'warn', or 'error'"
            raise ValueError(message)
        self._core = core
        self._mode = mode
        self._verified = mode == "off"

    async def verify(self) -> None:
        if self._verified:
            return
        self._verified = True
        try:
            catalog = await self._core.catalog.metrics()
            compatible = (
                catalog.client_schema_version == CLIENT_SCHEMA_VERSION
                and catalog.json_schema_dialect == JSON_SCHEMA_DIALECT
                and catalog.catalog_fingerprint == CATALOG_FINGERPRINT
            )
            detail = "server catalog does not match the generated client contract"
        except (LyraAPIError, RuntimeError, ValueError) as exc:
            compatible = False
            detail = f"could not verify the server catalog: {{exc}}"
        if compatible:
            return
        if self._mode == "error":
            raise CatalogCompatibilityError(detail)
        warnings.warn(detail, CatalogCompatibilityWarning, stacklevel=3)
"""
    )


def _render_metrics(
    catalog: MetricCatalogResponse,
    fields_by_metric: dict[str, list[_FieldSpec]],
    model_exports: list[str],
) -> str:
    if not catalog.metrics:
        return (
            GENERATED_HEADER
            + """from lyra.api import AsyncLyraClient, LyraClient

from ._runtime import AsyncCatalogVerifier, CatalogVerifier


class Metrics:
    def __init__(self, core: LyraClient, verifier: CatalogVerifier) -> None:
        self._core = core
        self._verifier = verifier


class AsyncMetrics:
    def __init__(
        self,
        core: AsyncLyraClient,
        verifier: AsyncCatalogVerifier,
    ) -> None:
        self._core = core
        self._verifier = verifier


__all__ = ["AsyncMetrics", "Metrics"]
"""
        )
    annotations = " ".join(
        field.annotation for fields in fields_by_metric.values() for field in fields
    )
    request_names = {f"{_pascal(metric.name)}Request" for metric in catalog.metrics}
    used_model_names = sorted(
        request_names
        | {
            name
            for name in model_exports
            if re.search(rf"\b{re.escape(name)}\b", annotations)
        }
    )
    sdk_names = sorted(
        {
            "TableJobResult" if metric.output.kind == "table" else "FileJobResult"
            for metric in catalog.metrics
        }
    )
    if "BoundsReference" in annotations:
        sdk_names.append("BoundsReference")
    if "LocationReference" in annotations:
        sdk_names.append("LocationReference")
    json_value_imports = (
        ["from lyra.sdk.types import JsonValue"] if "JsonValue" in annotations else []
    )
    if any(metric.output.kind == "file" for metric in catalog.metrics):
        os_imports = ["import os"]
    else:
        os_imports = []
    chunks = [
        GENERATED_HEADER.rstrip(),
        *os_imports,
        "from typing import cast",
        "",
        *_import_block(
            "lyra.api",
            [
                "AsyncJobHandle",
                "AsyncLyraClient",
                "JobHandle",
                "LyraClient",
                "RunOptions",
                "SubmitOptions",
            ],
        ),
        *_import_block("lyra.sdk", sorted(sdk_names)),
        *json_value_imports,
        "",
        *_import_block("._models", used_model_names),
        *_import_block(
            "._runtime",
            [
                "OMITTED",
                "AsyncCatalogVerifier",
                "CatalogVerifier",
                "OmittedType",
                "validate_metric_arguments",
            ],
        ),
        "",
        "",
    ]
    for metric in catalog.metrics:
        chunks.append(
            _render_metric_class(metric, fields_by_metric[metric.name], async_=False)
        )
        chunks.extend(["", ""])
        chunks.append(
            _render_metric_class(metric, fields_by_metric[metric.name], async_=True)
        )
        chunks.extend(["", ""])
    sync_names = [f"{_pascal(metric.name)}Metric" for metric in catalog.metrics]
    async_names = [f"Async{_pascal(metric.name)}Metric" for metric in catalog.metrics]
    chunks.extend(
        [
            "class Metrics:",
            (
                "    def __init__(self, core: LyraClient, "
                "verifier: CatalogVerifier) -> None:"
            ),
            *[
                (
                    f"        self.{metric.name} = {_pascal(metric.name)}Metric("
                    "core, verifier)"
                )
                for metric in catalog.metrics
            ],
            "",
            "",
            "class AsyncMetrics:",
            (
                "    def __init__(self, core: AsyncLyraClient, "
                "verifier: AsyncCatalogVerifier) -> None:"
            ),
            *[
                (
                    f"        self.{metric.name} = Async{_pascal(metric.name)}Metric("
                    "core, verifier)"
                )
                for metric in catalog.metrics
            ],
            "",
            "",
            _all_block(sorted(["Metrics", "AsyncMetrics", *sync_names, *async_names])),
        ]
    )
    return "\n".join(chunks) + "\n"


def _render_client() -> str:
    return (
        GENERATED_HEADER
        + """from typing import Literal, NotRequired, TypedDict, Unpack

from lyra.api import AsyncLyraClient, LyraClient

from ._metrics import AsyncMetrics, Metrics
from ._runtime import AsyncCatalogVerifier, CatalogVerifier


class _ClientOptions(TypedDict):
    timeout: NotRequired[float]
    headers: NotRequired[dict[str, str] | None]
    agent_api_key: NotRequired[str | None]
    secure: NotRequired[bool]
    verify_catalog: NotRequired[Literal["off", "warn", "error"]]


class Client:
    def __init__(
        self,
        host: str,
        **options: Unpack[_ClientOptions],
    ) -> None:
        core = LyraClient(
            host,
            options.get("timeout", 30.0),
            options.get("headers"),
            agent_api_key=options.get("agent_api_key"),
            secure=options.get("secure", True),
        )
        self._core = core
        self.health = core.health
        self.lookups = core.lookups
        self.catalog = core.catalog
        self.jobs = core.jobs
        self.results = core.results
        self.raw = core.raw
        verifier = CatalogVerifier(core, options.get("verify_catalog", "warn"))
        self.metrics = Metrics(core, verifier)


class AsyncClient:
    def __init__(
        self,
        host: str,
        **options: Unpack[_ClientOptions],
    ) -> None:
        core = AsyncLyraClient(
            host,
            options.get("timeout", 30.0),
            options.get("headers"),
            agent_api_key=options.get("agent_api_key"),
            secure=options.get("secure", True),
        )
        self._core = core
        self.health = core.health
        self.lookups = core.lookups
        self.catalog = core.catalog
        self.jobs = core.jobs
        self.results = core.results
        self.raw = core.raw
        verifier = AsyncCatalogVerifier(
            core,
            options.get("verify_catalog", "warn"),
        )
        self.metrics = AsyncMetrics(core, verifier)


__all__ = ["AsyncClient", "Client"]
"""
    )


def _render_contract(catalog: MetricCatalogResponse) -> str:
    return (
        GENERATED_HEADER
        + f"""CLIENT_SCHEMA_VERSION = {catalog.client_schema_version}
JSON_SCHEMA_DIALECT = {_literal(catalog.json_schema_dialect)}
CATALOG_FINGERPRINT = {_literal(catalog.catalog_fingerprint)}
GENERATOR_NAME = "lyra-client"
GENERATOR_VERSION = {_literal(_generator_version())}

__all__ = [
    "CATALOG_FINGERPRINT",
    "CLIENT_SCHEMA_VERSION",
    "GENERATOR_NAME",
    "GENERATOR_VERSION",
    "JSON_SCHEMA_DIALECT",
]
"""
    )


def _render_init(catalog: MetricCatalogResponse, model_exports: list[str]) -> str:
    requests = [f"{_pascal(metric.name)}Request" for metric in catalog.metrics]
    exports = sorted(
        {
            "AsyncClient",
            "Client",
            "BoundsReference",
            "CVEGEOList",
            "GeoJSONBounds",
            "GeoJSONLocation",
            "LocationReference",
            "MetZoneCode",
            "CatalogCompatibilityError",
            "CatalogCompatibilityWarning",
            "MetricArgumentsError",
            *model_exports,
            *requests,
        }
    )
    lines = [GENERATED_HEADER.rstrip()]
    lines.extend(
        _import_block(
            "lyra.sdk",
            [
                "BoundsReference",
                "CVEGEOList",
                "GeoJSONBounds",
                "GeoJSONLocation",
                "LocationReference",
                "MetZoneCode",
            ],
        )
    )
    lines.extend(["", "from ._client import AsyncClient, Client"])
    if model_exports:
        lines.extend(_import_block("._models", sorted(set(model_exports))))
    lines.extend(
        _import_block(
            "._runtime",
            [
                "CatalogCompatibilityError",
                "CatalogCompatibilityWarning",
                "MetricArgumentsError",
            ],
        )
    )
    lines.extend(["", _all_block(exports), ""])
    return "\n".join(lines)


def _resolve_local_reference(
    schema: JsonObject,
    metric_name: str,
    reference: str,
) -> None:
    if not reference.startswith("#/"):
        msg = f"metric {metric_name!r} has unsupported reference {reference!r}"
        raise ClientGenerationError(msg)
    value: object = schema
    for raw_part in reference[2:].split("/"):
        part = raw_part.replace("~1", "/").replace("~0", "~")
        if not isinstance(value, dict) or part not in value:
            msg = f"metric {metric_name!r} has broken reference {reference!r}"
            raise ClientGenerationError(msg)
        value = value[part]


def _validate_local_references(schema: JsonObject, metric_name: str) -> None:

    def walk(value: JsonValue) -> None:
        if isinstance(value, dict):
            reference = value.get("$ref")
            if isinstance(reference, str):
                _resolve_local_reference(schema, metric_name, reference)
            for item in value.values():
                walk(item)
        elif isinstance(value, list):
            for item in value:
                walk(item)

    walk(schema)


def _validate_catalog(catalog: MetricCatalogResponse) -> None:
    if catalog.client_schema_version != CLIENT_SCHEMA_VERSION:
        msg = f"unsupported client schema version: {catalog.client_schema_version}"
        raise ClientGenerationError(msg)
    if catalog.json_schema_dialect != JSON_SCHEMA_DIALECT:
        msg = f"unsupported JSON Schema dialect: {catalog.json_schema_dialect}"
        raise ClientGenerationError(msg)
    seen: set[str] = set()
    for metric in catalog.metrics:
        if not _PUBLIC_NAME.fullmatch(metric.name) or metric.name.startswith("lyra_"):
            msg = f"invalid public metric name: {metric.name!r}"
            raise ClientGenerationError(msg)
        generated_name = _pascal(metric.name).casefold()
        if generated_name in seen:
            msg = f"metric naming collision for {metric.name!r}"
            raise ClientGenerationError(msg)
        seen.add(generated_name)
        if metric.request_schema.get("$schema") != JSON_SCHEMA_DIALECT:
            msg = f"metric {metric.name!r} does not declare {JSON_SCHEMA_DIALECT}"
            raise ClientGenerationError(msg)
        try:
            Draft202012Validator.check_schema(metric.request_schema)
        except SchemaError as exc:
            msg = f"metric {metric.name!r} has invalid request schema: {exc.message}"
            raise ClientGenerationError(msg) from exc
        _validate_local_references(metric.request_schema, metric.name)


def _render_models_source(
    model_sections: list[str],
) -> str:
    if not model_sections:
        return GENERATED_HEADER + "__all__: list[str] = []\n"
    combined_models = "\n\n\n".join(model_sections)
    model_header_lines = [GENERATED_HEADER.rstrip()]
    standard_imports: list[str] = []
    if "json.loads" in combined_models:
        standard_imports.append("import json")
    if "(StrEnum)" in combined_models:
        standard_imports.append("from enum import StrEnum")
    typing_names = [
        name
        for name in ("Literal", "cast")
        if f"{name}(" in combined_models or f"{name}[" in combined_models
    ]
    if typing_names:
        standard_imports.append(f"from typing import {', '.join(typing_names)}")
    if standard_imports:
        model_header_lines.extend([*standard_imports, ""])
    sdk_names = [
        name
        for name in ("BoundsReference", "LocationReference")
        if name in combined_models
    ]
    if sdk_names:
        model_header_lines.extend(_import_block("lyra.sdk", sdk_names))
    if "JsonValue" in combined_models:
        model_header_lines.append("from lyra.sdk.types import JsonValue")
    pydantic_names = ["BaseModel", "ConfigDict"]
    if "Field(" in combined_models:
        pydantic_names.append("Field")
    model_header_lines.extend(_import_block("pydantic", pydantic_names))
    if "OMITTED" in combined_models:
        model_header_lines.extend(["", "from ._runtime import OMITTED"])
    models_header = "\n".join(model_header_lines) + "\n\n\n"
    return models_header + combined_models + "\n"


def render_package(catalog: MetricCatalogResponse) -> tuple[dict[str, str], list[str]]:
    """Render all generator-owned files without touching a destination."""

    _validate_catalog(catalog)
    catalog = catalog.model_copy(
        update={"metrics": sorted(catalog.metrics, key=lambda metric: metric.name)}
    )
    model_sections: list[str] = []
    model_exports: list[str] = []
    fields_by_metric: dict[str, list[_FieldSpec]] = {}
    generation_warnings: list[str] = []
    for metric in sorted(catalog.metrics, key=lambda item: item.name):
        emitter = _SchemaEmitter(metric)
        source, fields, metric_warnings = emitter.emit()
        body = (
            "class _GeneratedModel"
            + source.split("class _GeneratedModel", maxsplit=1)[1]
        )
        body = body.split("\n__all__ =", maxsplit=1)[0].rstrip()
        if model_sections:
            next_class = body.find("\n\nclass ")
            if next_class == -1:
                msg = f"metric {metric.name!r} did not emit a request model"
                raise ClientGenerationError(msg)
            body = body[next_class + 2 :]
        model_sections.append(body)
        model_exports.extend([*emitter.enums, *emitter.models])
        fields_by_metric[metric.name] = fields
        generation_warnings.extend(metric_warnings)

    models_source = _render_models_source(model_sections)
    files = {
        "__init__.py": _render_init(catalog, model_exports),
        "_client.py": _render_client(),
        "_contract.py": _render_contract(catalog),
        "_metrics.py": _render_metrics(catalog, fields_by_metric, model_exports),
        "_models.py": models_source,
        "_runtime.py": _render_runtime(catalog),
        "py.typed": "",
    }
    owned = sorted([*files, MANIFEST_NAME])
    files[MANIFEST_NAME] = json.dumps({"generated_files": owned}, indent=2) + "\n"
    return files, generation_warnings


def _validate_rendered_package(package: str, directory: Path) -> None:
    for path in directory.rglob("*.py"):
        ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
    module_name = f"_lyra_generated_validation_{package}"
    spec = importlib.util.spec_from_file_location(
        module_name,
        directory / "__init__.py",
        submodule_search_locations=[str(directory)],
    )
    if spec is None or spec.loader is None:
        msg = "could not create generated package import spec"
        raise ClientGenerationError(msg)
    module = importlib.util.module_from_spec(spec)
    sys.modules[module_name] = module
    try:
        spec.loader.exec_module(module)
    except Exception as exc:
        msg = f"generated package failed import validation: {exc}"
        raise ClientGenerationError(msg) from exc
    finally:
        for name in list(sys.modules):
            if name == module_name or name.startswith(f"{module_name}."):
                del sys.modules[name]


def _write_rendered(files: dict[str, str], destination: Path) -> None:
    old_owned: set[str] = set()
    manifest_path = destination / MANIFEST_NAME
    if manifest_path.is_file():
        try:
            manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
            values = manifest.get("generated_files", [])
            if isinstance(values, list):
                old_owned = {str(value) for value in values}
        except (json.JSONDecodeError, OSError):
            old_owned = set()
    destination.mkdir(parents=True, exist_ok=True)
    new_owned = set(files)
    for relative in sorted(old_owned - new_owned):
        target = destination / relative
        if target.is_file() and target.resolve().is_relative_to(destination.resolve()):
            target.unlink()
    for relative, content in files.items():
        target = destination / relative
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")


def _stale_diff(files: dict[str, str], destination: Path) -> str:
    chunks: list[str] = []
    for relative, expected in sorted(files.items()):
        target = destination / relative
        actual = target.read_text(encoding="utf-8") if target.is_file() else ""
        if actual == expected:
            continue
        diff = difflib.unified_diff(
            actual.splitlines(),
            expected.splitlines(),
            fromfile=f"current/{relative}",
            tofile=f"generated/{relative}",
            lineterm="",
            n=2,
        )
        chunks.extend(list(diff)[:12])
    manifest = destination / MANIFEST_NAME
    if manifest.is_file():
        try:
            old = json.loads(manifest.read_text(encoding="utf-8"))
            chunks.extend(
                f"stale generated file: {relative}"
                for relative in old.get("generated_files", [])
                if relative not in files and (destination / relative).exists()
            )
        except (json.JSONDecodeError, OSError, TypeError):
            pass
    return "\n".join(chunks)


def generate_client(
    catalog: MetricCatalogResponse,
    *,
    package: str,
    output: Path,
    check: bool = False,
) -> bool:
    """Generate a package, returning false only when check mode finds drift."""

    if not _PACKAGE_NAME.fullmatch(package):
        msg = f"package must be one Python identifier, got {package!r}"
        raise ClientGenerationError(msg)
    files, generation_warnings = render_package(catalog)
    for message in generation_warnings:
        warnings.warn(message, ClientGenerationWarning, stacklevel=2)
    with tempfile.TemporaryDirectory(prefix="lyra-client-") as temp_name:
        package_directory = Path(temp_name) / package
        package_directory.mkdir()
        _write_rendered(files, package_directory)
        _validate_rendered_package(package, package_directory)
    if check:
        diff = _stale_diff(files, output)
        if diff:
            sys.stderr.write(f"{diff}\n")
            return False
        return True
    _write_rendered(files, output)
    return True


def build_parser() -> argparse.ArgumentParser:
    """Build the command-line parser used by ``lyra-client``."""

    parser = argparse.ArgumentParser(
        prog="lyra-client",
        description="Pull metric catalogs and generate typed Python clients.",
    )
    commands = parser.add_subparsers(dest="command", required=True)
    catalog = commands.add_parser(
        "catalog",
        help="Manage local metric catalog snapshots.",
        description="Manage local metric catalog snapshots.",
    )
    catalog_commands = catalog.add_subparsers(dest="catalog_command", required=True)
    pull = catalog_commands.add_parser(
        "pull",
        help="Fetch and validate the public metric catalog.",
        description=(
            "Fetch /metrics and write a canonical catalog snapshot for client "
            "generation."
        ),
    )
    pull.add_argument(
        "--host",
        required=True,
        metavar="HOST",
        help="Lyra host or base URL; HTTPS is used when no scheme is provided.",
    )
    pull.add_argument(
        "--insecure",
        action="store_true",
        help="Use HTTP when --host has no explicit scheme.",
    )
    pull.add_argument(
        "--output",
        type=Path,
        default=Path("lyra-catalog.json"),
        metavar="PATH",
        help="Catalog snapshot path (default: lyra-catalog.json).",
    )
    generate = commands.add_parser(
        "generate",
        help="Generate a typed Python package from a catalog snapshot.",
        description="Generate a typed Python package from a metric catalog snapshot.",
    )
    generate.add_argument(
        "--catalog",
        required=True,
        type=Path,
        metavar="PATH",
        help="Catalog snapshot created by 'catalog pull'.",
    )
    generate.add_argument(
        "--package",
        required=True,
        metavar="NAME",
        help="Generated package name; must be one valid Python identifier.",
    )
    generate.add_argument(
        "--output",
        required=True,
        type=Path,
        metavar="DIRECTORY",
        help="Destination directory for the generated package files.",
    )
    generate.add_argument(
        "--check",
        action="store_true",
        help="Check for stale output without writing files; exit 1 on drift.",
    )
    return parser


def _run_command(args: argparse.Namespace) -> int:
    if args.command == "catalog":
        catalog = pull_catalog(args.host, insecure=args.insecure)
        args.output.write_text(canonical_catalog_json(catalog), encoding="utf-8")
        return 0
    payload = json.loads(args.catalog.read_text(encoding="utf-8"))
    catalog = MetricCatalogResponse.model_validate(payload)
    clean = generate_client(
        catalog,
        package=args.package,
        output=args.output,
        check=args.check,
    )
    return 0 if clean else 1


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    try:
        return _run_command(args)
    except (
        ClientGenerationError,
        OSError,
        ValueError,
        requests.RequestException,
    ) as exc:
        sys.stderr.write(f"lyra-client: {exc}\n")
        return 2


if __name__ == "__main__":
    raise SystemExit(main())


__all__ = [
    "ClientGenerationError",
    "ClientGenerationWarning",
    "build_parser",
    "canonical_catalog_json",
    "generate_client",
    "main",
    "pull_catalog",
    "render_package",
]
