name: Validate AsyncAPI

on:
  workflow_dispatch:
  push:
    paths:
      - asyncapi.yaml
  pull_request:
    paths:
      - asyncapi.yaml

jobs:
  validate-asyncapi:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Validate asyncapi.yaml
        run: npx -y @asyncapi/cli@latest validate asyncapi.yaml
